version: "3.8"

services:
  mongo:
    image: mongo:latest
    restart: always
    container_name: mongo_bd2
    hostname: host-mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"

