version: "3.7"

services:
  redis:
    image: redis:6.2-alpine
    container_name: redis
    restart: always
    ports:
      - '6379:6379'
    command: redis-server --loglevel warning --requirepass password
    volumes:
      - ./data:/data