version: "3.2"

services:
  redis:
    image: redis:alpine
    container_name: redis
    restart: always
    ports:
      - '6379:6379'
    command: redis-server --loglevel warning --requirepass password
    volumes:
      - ./data:/data
    environment:
      - REDIS_REPLICATION_MODE=master